### PR TITLE
Update version from v0.1.6 to v0.1.7

### PR DESCRIPTION
**Pull request by MarkRivers**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
@MarkRivers The configuration of the servers has changed since this recipe was last built. Rerendering the feedstock automatically updates the server configuration based on the recipe. Also, in `meta.yaml`, you will need to update the hash of the source tarball like the bot did in #11.

@conda-forge-admin, please rerender 

Closes #11.

**Comment by carterbox** [comment]
Closes #10

**Comment by MarkRivers** [comment]
@carterbox I have updated the sha256 in meta.yaml, and it is has been re-rendered.  All checks have passed.  OK to merge?

**Comment by carterbox** [comment]
LGTM, but I am not a maintainer of this feedstock, please ask @decarlof or one of the other persons from the Reviewers section of this PR.

**Comment by MarkRivers** [comment]
Now that this has been merged how long should I expect it to take before the new version is available on conda-forge?

It has been 15 minutes and I don't see it yet.
```
(tomo_test) C:\Data\Rivers\Rivers>conda search -c conda-forge dxchange
Loading channels: done
# Name                       Version           Build  Channel
dxchange                       0.1.1          py27_0  conda-forge
dxchange                       0.1.1          py34_0  conda-forge
dxchange                       0.1.1          py35_0  conda-forge
dxchange                       0.1.3          py27_0  conda-forge
dxchange                       0.1.3          py35_0  conda-forge
dxchange                       0.1.3          py36_0  conda-forge
dxchange                       0.1.4          py27_0  conda-forge
dxchange                       0.1.4          py35_0  conda-forge
dxchange                       0.1.4          py36_0  conda-forge
dxchange                       0.1.5       py27_1000  conda-forge
dxchange                       0.1.5          py35_0  conda-forge
dxchange                       0.1.5       py36_1000  conda-forge
dxchange                       0.1.5       py37_1000  conda-forge
dxchange                       0.1.5         py_1001  conda-forge
dxchange                       0.1.6    pyhd3deb0d_0  conda-forge
```

**Pull request merged**
